replicaCount: 1

image:
  repository: vulnerables/web-dvwa
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}