apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dvwa-db
  labels:
    app: dvwa
    component: mysql
spec:
  serviceName: dvwa-db
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
      component: mysql
  template:
    metadata:
      labels:
        app: dvwa
        component: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: p@ssw0rd
            - name: MYSQL_DATABASE
              value: dvwa
            - name: MYSQL_USER
              value: dvwa
            - name: MYSQL_PASSWORD
              value: p@ssw0rd
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u dvwa -pp@ssw0rd
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -u dvwa -pp@ssw0rd
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-db
  labels:
    app: dvwa
    component: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      name: mysql
      targetPort: mysql
  selector:
    app: dvwa
    component: mysql