apiVersion: v1
kind: Service
metadata:
  name: {{ include "dvwa.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "dvwa.selectorLabels" . | nindent 4 }}